title: Insert title here
author: Add author's name here
email: your-email-address@comes-here.com
description: > # this means to ignore newlines until "baseurl:"
  This is the place where it is a good idea to add a awesome description. However since I do not have awesome ideas, this will have to suffice.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
